using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class HardcodedLevels{
    public static string level1 = " {\"dimension\":2, \"xTiles\":[{\"yTiles\":[{\"zTiles\":[{\"hasCube\":true},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":true},{\"hasCube\":true}]}]},{\"yTiles\":[{\"zTiles\":[{\"hasCube\":true},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":false}]}]}]}";
    public static string level2 = "{ \"dimension\":2, \"xTiles\":[{\"yTiles\":[{\"zTiles\":[{\"hasCube\":true},{\"hasCube\":false}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":false}]}]},{\"yTiles\":[{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":true}]}]}]}";
    public static string level3 = "{ \"dimension\":2, \"xTiles\":[{\"yTiles\":[{\"zTiles\":[{\"hasCube\":true},{\"hasCube\":false}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":true}]}]},{\"yTiles\":[{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":true},{\"hasCube\":false}]}]}]}";
    public static string level4 = "{ \"dimension\":3, \"xTiles\":[{\"yTiles\":[{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":true},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":false},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":false},{\"hasCube\":false}]}]},{\"yTiles\":[{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":true},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":false},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":false},{\"hasCube\":false}]}]},{\"yTiles\":[{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":false},{\"hasCube\":false}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":false},{\"hasCube\":false}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":false},{\"hasCube\":false}]}]}]}";
    public static string level5 = "{ \"dimension\":3, \"xTiles\":[{\"yTiles\":[{\"zTiles\":[{\"hasCube\":true},{\"hasCube\":true},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":false},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":false},{\"hasCube\":true}]}]},{\"yTiles\":[{\"zTiles\":[{\"hasCube\":true},{\"hasCube\":true},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":true},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":true},{\"hasCube\":true}]}]},{\"yTiles\":[{\"zTiles\":[{\"hasCube\":true},{\"hasCube\":true},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":true},{\"hasCube\":true},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":true},{\"hasCube\":true},{\"hasCube\":false}]}]}]}";
    public static string level6 = "{ \"dimension\":3, \"xTiles\":[{\"yTiles\":[{\"zTiles\":[{\"hasCube\":true},{\"hasCube\":false},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":true},{\"hasCube\":false},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":true},{\"hasCube\":false},{\"hasCube\":true}]}]},{\"yTiles\":[{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":true},{\"hasCube\":false}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":true},{\"hasCube\":false}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":true},{\"hasCube\":false}]}]},{\"yTiles\":[{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":false},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":false},{\"hasCube\":true}]},{\"zTiles\":[{\"hasCube\":false},{\"hasCube\":false},{\"hasCube\":true}]}]}]}";
}
